/**
 * Averrow — robots.txt for the public corporate site.
 *
 * After the R6/R7 cutover, sitemap.xml is generated by
 * scripts/generate-sitemap.mjs in packages/averrow-marketing and
 * shipped as a static asset under public/sitemap.xml. The Worker
 * no longer renders sitemap.xml dynamically; this file keeps only
 * the robots.txt generator + a thin sitemap fallback that lists
 * the Worker-only routes in case ASSETS misses the static one.
 */

export function renderRobotsTxt(): string {
  // Shared disallow list — kept identical across the wildcard block and
  // every explicit AI-crawler block below.
  const disallow = [
    "/v2/",
    "/api/",
    "/admin-portal/",
    "/internal-staff/",
    "/internal-docs/",
    "/team-directory/",
    "/staff-contacts/",
  ];

  // Explicitly welcome AI crawlers (they get Allow: / plus the same
  // disallow rules as everyone else).
  const aiCrawlers = [
    "GPTBot",
    "OAI-SearchBot",
    "ChatGPT-User",
    "ClaudeBot",
    "PerplexityBot",
    "Google-Extended",
    "CCBot",
    "Amazonbot",
    "Applebot-Extended",
  ];

  const disallowLines = disallow.map((p) => `Disallow: ${p}`).join("\n");

  const aiBlocks = aiCrawlers
    .map((name) => `User-agent: ${name}\nAllow: /\n${disallowLines}`)
    .join("\n\n");

  return `User-agent: *
Allow: /
${disallowLines}

${aiBlocks}

# Sitemap
Sitemap: https://averrow.com/sitemap.xml
`;
}

/**
 * Minimal fallback sitemap returned by the Worker's /sitemap.xml
 * route handler if the static asset isn't served by ASSETS for any
 * reason. Lists Worker-only routes only — Astro pages are covered
 * by the static sitemap generated at marketing-build time.
 */
export function renderSitemapXml(): string {
  const staticPages = [
    "/scan",
    "/status",
    "/team",
    "/privacy",
    "/terms",
  ];

  const urls = staticPages.map(
    (p) =>
      `  <url><loc>https://averrow.com${p}</loc><changefreq>weekly</changefreq></url>`,
  );

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.join("\n")}
</urlset>
`;
}
